# Generated by Django 3.2.20 on 2023-10-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='programs',
            field=models.ManyToManyField(to='projects.Program'),
        ),
    ]
