# Generated by Django 3.2.20 on 2023-10-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_attribute_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataversion',
            name='data_type',
            field=models.CharField(choices=[('F', 'File Data'), ('I', 'Image Data'), ('C', 'Clinical Data'), ('B', 'Biospecimen Data'), ('M', 'Mutation Data'), ('P', 'Protein Data'), ('T', 'File Type Data')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='dataversion',
            name='version',
            field=models.CharField(max_length=64),
        ),
    ]
