# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160614_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'studies'},
        ),
        migrations.AlterModelOptions(
            name='user_data_tables',
            options={'verbose_name': 'user data table', 'verbose_name_plural': 'user data tables'},
        ),
    ]
