# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160826_0945'),
        ('projects', '0003_auto_20160826_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_BQ_Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bq_table_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='study_bq_tables',
            name='user_data_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.User_Data_Tables'),
        ),
        migrations.AddField(
            model_name='user_data_tables',
            name='google_bq_dataset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.BqDataset'),
            preserve_default=False,
        ),
    ]
