# Generated by Django 3.2.20 on 2023-10-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20231020_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='aggregate_level',
            field=models.CharField(default='case_barcode', max_length=128),
        ),
        migrations.AddField(
            model_name='datasource',
            name='count_col',
            field=models.CharField(default='case_barcode', max_length=128),
        ),
    ]
