# Generated by Django 3.2.20 on 2023-10-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20231020_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='datanode',
            name='programs',
            field=models.ManyToManyField(to='projects.Program'),
        ),
    ]
