# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20161005_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Program',
        ),
        migrations.RenameModel(
            old_name='Project_Last_View',
            new_name='Program_Last_View',
        ),
        migrations.RenameField(
            model_name='program_last_view',
            old_name='project',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='project',
            new_name='program',
        ),
        migrations.AlterField(
            model_name='study',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
