# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20161114_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Study',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Study_BQ_Tables',
            new_name='Project_BQ_Tables',
        ),
        migrations.RenameModel(
            old_name='Study_Last_View',
            new_name='Project_Last_View',
        ),
        migrations.RenameField(
            model_name='project_last_view',
            old_name='study',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='user_data_tables',
            old_name='study',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='user_feature_definitions',
            old_name='study',
            new_name='project',
        ),
    ]
