# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20161114_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'projects'},
        ),
    ]
