# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-21 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20161114_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_Annotation_Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annot_table', models.CharField(max_length=100, null=True)),
                ('annot2sample_table', models.CharField(max_length=100, null=True)),
                ('annot2biospec_table', models.CharField(max_length=100, null=True)),
                ('annot2clin_table', models.CharField(max_length=100, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Program')),
            ],
            options={
                'verbose_name': 'Public Annotation Table',
                'verbose_name_plural': 'Public Annotation Tables',
            },
        ),
        migrations.CreateModel(
            name='Public_Data_Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.CharField(max_length=25, null=True)),
                ('data_table', models.CharField(max_length=100)),
                ('annot2data_table', models.CharField(max_length=100, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Program')),
            ],
            options={
                'verbose_name': 'Public Data Table',
                'verbose_name_plural': 'Public Data Tables',
            },
        ),
        migrations.CreateModel(
            name='Public_Metadata_Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples_table', models.CharField(max_length=100)),
                ('attr_table', models.CharField(max_length=100)),
                ('clin_table', models.CharField(max_length=100)),
                ('biospec_table', models.CharField(max_length=100)),
                ('sample_data_availability_table', models.CharField(max_length=100)),
                ('sample_data_type_availability_table', models.CharField(max_length=100)),
                ('annot_tables', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Public_Annotation_Tables')),
                ('data_tables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Public_Data_Tables')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Program')),
            ],
            options={
                'verbose_name': 'Public Metadata Table',
                'verbose_name_plural': 'Public Metadata Tables',
            },
        ),
    ]
