# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-07 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_public_annotation_tables_public_data_tables_public_metadata_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_metadata_tables',
            name='projects_table',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
