# Generated by Django 2.2.10 on 2020-05-09 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180412_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('N', 'Continuous Numeric'), ('C', 'Categorical String'), ('T', 'Text'), ('S', 'String')], default='C', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('is_cross_collex', models.BooleanField(default=False)),
                ('preformatted_values', models.BooleanField(default=False)),
                ('default_ui_display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16)),
                ('data_type', models.CharField(choices=[('F', 'File Data'), ('I', 'Image Data'), ('C', 'Clinical Data'), ('B', 'Biospecimen Data'), ('M', 'Mutation Data')], default='C', max_length=1)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('programs', models.ManyToManyField(to='projects.Program')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('shared_id_col', models.CharField(default='PatientID', max_length=128)),
                ('source_type', models.CharField(choices=[('S', 'Solr Data Collection'), ('B', 'BigQuery Table')], default='S', max_length=1)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.DataVersion')),
            ],
            options={
                'unique_together': {('name', 'version', 'source_type')},
            },
        ),
        migrations.CreateModel(
            name='Attribute_Ranges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('F', 'Float'), ('I', 'Integer')], default='I', max_length=1)),
                ('include_lower', models.BooleanField(default=True)),
                ('include_upper', models.BooleanField(default=False)),
                ('unbounded', models.BooleanField(default=True)),
                ('first', models.CharField(default='10', max_length=128)),
                ('last', models.CharField(default='80', max_length=128)),
                ('gap', models.CharField(default='10', max_length=128)),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='data_sources',
            field=models.ManyToManyField(to='projects.DataSource'),
        ),
        migrations.CreateModel(
            name='Attribute_Display_Values',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_value', models.CharField(max_length=256)),
                ('display_value', models.CharField(max_length=256)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute')),
            ],
            options={
                'unique_together': {('raw_value', 'attribute')},
            },
        ),
    ]
