# Generated by Django 2.2.10 on 2020-06-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_datasource_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_ranges',
            name='unit',
            field=models.CharField(default='1', max_length=128),
        ),
        migrations.AlterField(
            model_name='dataversion',
            name='data_type',
            field=models.CharField(choices=[('F', 'File Data'), ('I', 'Image Data'), ('C', 'Clinical Data'), ('B', 'Biospecimen Data'), ('M', 'Mutation Data'), ('D', 'File Data Availability')], default='C', max_length=1),
        ),
        migrations.CreateModel(
            name='Attribute_Tooltips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
                ('tooltip', models.CharField(max_length=256)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute')),
            ],
            options={
                'unique_together': {('value', 'attribute')},
            },
        ),
    ]
