# Generated by Django 2.2.13 on 2021-01-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200619_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('data_sources', models.ManyToManyField(to='projects.DataSource')),
            ],
        ),
    ]
