# Generated by Django 2.2.13 on 2021-01-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_datanode'),
    ]

    operations = [
        migrations.AddField(
            model_name='datanode',
            name='short_name',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
