# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 20:54
from __future__ import unicode_literals

import data_upload.models
from django.db import migrations, models
import google_helpers.cloud_file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedfile',
            name='file',
            field=models.FileField(storage=google_helpers.cloud_file_storage.CloudFileStorage(), upload_to=data_upload.models.get_user_bucket),
        ),
    ]
