# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-21 22:14
from __future__ import unicode_literals

import data_upload.models
from django.db import migrations, models
import google_helpers.cloud_file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0002_auto_20160614_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedfile',
            name='file',
            field=models.FileField(max_length=255, storage=google_helpers.cloud_file_storage.CloudFileStorage(), upload_to=data_upload.models.get_user_bucket),
        ),
    ]
