# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-08 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0003_auto_20170321_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='message',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
