# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_account', models.CharField(max_length=1024)),
                ('authorized_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AuthorizedDataset')),
                ('google_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.GoogleProject')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthorizedDatasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AuthorizedDataset')),
                ('nih_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.NIH_User')),
            ],
        ),
    ]
