# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160608_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeddataset',
            name='acl_google_group',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authorizeddataset',
            name='whitelist_id',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nih_user',
            name='linked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='authorized_dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AuthorizedDataset'),
        ),
    ]
