# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_authorizeddataset_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleproject',
            name='user',
        ),
        migrations.AddField(
            model_name='googleproject',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
