# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160715_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthorizeddatasets',
            name='nih_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.NIH_User'),
        ),
    ]
