# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160719_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='BqDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=155)),
                ('google_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.GoogleProject')),
            ],
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='user',
        ),
        migrations.AddField(
            model_name='bucket',
            name='google_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.GoogleProject'),
            preserve_default=False,
        ),
    ]
