# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-22 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160826_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccountAuthorizedDatasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_date', models.DateTimeField(auto_now=True)),
                ('authorized_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AuthorizedDataset')),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ServiceAccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='nih_user',
            name='dbGaP_authorized',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='active',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='authorized_dataset',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='authorized_date',
        ),
    ]
