# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-15 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_serviceaccount_authorized_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeddataset',
            name='duca_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
