# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-29 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_authorizeddataset_duca_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userauthorizeddatasets',
            unique_together=set([('nih_user', 'authorized_dataset')]),
        ),
    ]
