# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170828_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleproject',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
