# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_googleproject_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCFToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcf_user', models.CharField(max_length=128)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('nih_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.NIH_User')),
            ],
        ),
    ]
