# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180524_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='bucket_name',
            field=models.CharField(max_length=155, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bqdataset',
            unique_together=set([('google_project', 'dataset_name')]),
        ),
    ]
