# Generated by Django 3.2.20 on 2024-02-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200210_2240'),
        ('accounts', '0019_local_user_accounts'),
    ]

    operations = [
    ]
