# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-04 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0002_auto_20160614_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atrribute_Display_Values',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_value', models.CharField(max_length=256)),
                ('display_value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('N', 'Continuous Numeric'), ('C', 'Categorical')], default='C', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('is_cross_collex', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shared', models.ManyToManyField(to='sharing.Shared_Resource')),
            ],
        ),
        migrations.CreateModel(
            name='User_Feature_Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Feature_Definitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=200)),
                ('bq_map_id', models.CharField(max_length=200)),
                ('is_numeric', models.BooleanField(default=False)),
                ('shared_map_id', models.CharField(blank=True, max_length=128, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Collection')),
            ],
        ),
        migrations.AddField(
            model_name='user_feature_counts',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.User_Feature_Definitions'),
        ),
        migrations.AddField(
            model_name='collection',
            name='program',
            field=models.ManyToManyField(to='idc_collections.Program'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='collections',
            field=models.ManyToManyField(to='idc_collections.Collection'),
        ),
        migrations.AddField(
            model_name='atrribute_display_values',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='atrribute_display_values',
            unique_together=set([('raw_value', 'attribute')]),
        ),
    ]
