# Generated by Django 2.2.13 on 2020-09-16 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0002_auto_20160614_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('N', 'Continuous Numeric'), ('C', 'Categorical String'), ('M', 'Categorical Number'), ('T', 'Text'), ('S', 'String')], default='C', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('is_cross_collex', models.BooleanField(default=False)),
                ('preformatted_values', models.BooleanField(default=False)),
                ('units', models.CharField(blank=True, max_length=256, null=True)),
                ('default_ui_display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('tcia_collection_id', models.CharField(max_length=255, null=True)),
                ('nbia_collection_id', models.CharField(max_length=255, null=True)),
                ('collection_id', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('date_updated', models.DateField(null=True)),
                ('status', models.CharField(max_length=40, null=True)),
                ('access', models.CharField(max_length=40, null=True)),
                ('subject_count', models.IntegerField(default=0, null=True)),
                ('image_types', models.CharField(max_length=255, null=True)),
                ('cancer_type', models.CharField(max_length=128, null=True)),
                ('doi', models.CharField(max_length=255, null=True)),
                ('supporting_data', models.CharField(max_length=255, null=True)),
                ('analysis_artifacts', models.CharField(max_length=255, null=True)),
                ('species', models.CharField(max_length=64, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('collection_type', models.CharField(choices=[('A', 'Analysis'), ('O', 'Original')], default='O', max_length=1)),
                ('collections', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSetType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('data_type', models.CharField(choices=[('I', 'Image Data'), ('A', 'Clinical, Biospecimen, and Mutation Data'), ('D', 'Derived Data')], default='I', max_length=1)),
                ('set_type', models.CharField(choices=[('O', 'origin_set'), ('C', 'related_set'), ('R', 'derived_set')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('count_col', models.CharField(default='PatientID', max_length=128)),
                ('source_type', models.CharField(choices=[('S', 'Solr Data Collection'), ('B', 'BigQuery Table')], default='S', max_length=1)),
                ('data_sets', models.ManyToManyField(to='idc_collections.DataSetType')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingDataCommonsVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('version_number', models.CharField(max_length=128)),
                ('version_uid', models.CharField(max_length=128, null=True)),
                ('date_active', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shared', models.ManyToManyField(to='sharing.Shared_Resource')),
            ],
        ),
        migrations.CreateModel(
            name='User_Feature_Definitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=200)),
                ('bq_map_id', models.CharField(max_length=200)),
                ('is_numeric', models.BooleanField(default=False)),
                ('shared_map_id', models.CharField(blank=True, max_length=128, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='User_Feature_Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('count', models.IntegerField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.User_Feature_Definitions')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Program')),
                ('shared', models.ManyToManyField(to='sharing.Shared_Resource')),
            ],
        ),
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('idc_versions', models.ManyToManyField(to='idc_collections.ImagingDataCommonsVersion')),
                ('programs', models.ManyToManyField(to='idc_collections.Program')),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_src_col', models.CharField(max_length=64)),
                ('to_src_col', models.CharField(max_length=64)),
                ('from_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_data_source', to='idc_collections.DataSource')),
                ('to_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_data_source', to='idc_collections.DataSource')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='programs',
            field=models.ManyToManyField(to='idc_collections.Program'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='versions',
            field=models.ManyToManyField(to='idc_collections.DataVersion'),
        ),
        migrations.AddField(
            model_name='collection',
            name='data_versions',
            field=models.ManyToManyField(to='idc_collections.DataVersion'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Program'),
        ),
        migrations.CreateModel(
            name='Attribute_Ranges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('F', 'Float'), ('I', 'Integer')], default='I', max_length=1)),
                ('include_lower', models.BooleanField(default=True)),
                ('include_upper', models.BooleanField(default=False)),
                ('unbounded', models.BooleanField(default=True)),
                ('first', models.CharField(default='10', max_length=128)),
                ('last', models.CharField(default='80', max_length=128)),
                ('gap', models.CharField(default='10', max_length=128)),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute_Display_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=256)),
                ('category_display_name', models.CharField(max_length=256)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='data_sources',
            field=models.ManyToManyField(to='idc_collections.DataSource'),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('name', 'source_type')},
        ),
        migrations.CreateModel(
            name='Attribute_Set_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_record_search', models.CharField(blank=True, max_length=256, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Attribute')),
                ('datasettype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.DataSetType')),
            ],
            options={
                'unique_together': {('datasettype', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='Attribute_Display_Values',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_value', models.CharField(max_length=256)),
                ('display_value', models.CharField(max_length=256)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Attribute')),
            ],
            options={
                'unique_together': {('raw_value', 'attribute')},
            },
        ),
    ]
