# Generated by Django 2.2.13 on 2020-12-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(choices=[('N', 'Continuous Numeric'), ('C', 'Categorical String'), ('M', 'Categorical Number'), ('T', 'Text'), ('S', 'String'), ('D', 'Date')], default='C', max_length=1),
        ),
    ]
