# Generated by Django 2.2.10 on 2020-05-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='programs',
            field=models.ManyToManyField(to='idc_collections.Program'),
        ),
        migrations.AddField(
            model_name='dataversion',
            name='programs',
            field=models.ManyToManyField(to='idc_collections.Program'),
        ),
        migrations.AlterField(
            model_name='dataversion',
            name='data_type',
            field=models.CharField(choices=[('I', 'Image Data'), ('A', 'Clinical and Biospecimen Data'), ('D', 'Derived Data')], default='A', max_length=1),
        ),
    ]
