# Generated by Django 2.2.10 on 2020-08-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='name',
            new_name='collection_id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='short_name',
        ),
        migrations.AddField(
            model_name='attribute_set_type',
            name='display_set',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='access',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='cancer_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(choices=[('A', 'Analysis'), ('O', 'Original')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='collection',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='doi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='image_types',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='nbia_collection_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='species',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='subject_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='supporting_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='tcia_collection_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
