# Generated by Django 2.2 on 2020-01-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atrribute_Display_Values',
            new_name='Attribute_Display_Values',
        ),
    ]
