# Generated by Django 2.2 on 2020-01-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0002_auto_20200116_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
