# Generated by Django 2.2.10 on 2020-08-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0002_auto_20200821_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_set_type',
            name='child_record_search',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
