# Generated by Django 2.2.13 on 2021-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0003_attribute_tooltips'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingdatacommonsversion',
            name='case_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagingdatacommonsversion',
            name='collex_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagingdatacommonsversion',
            name='data_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imagingdatacommonsversion',
            name='series_count',
            field=models.IntegerField(default=0),
        ),
    ]
