# Generated by Django 2.2 on 2020-01-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0003_auto_20200117_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='preformatted_values',
            field=models.BooleanField(default=False),
        ),
    ]
