# Generated by Django 2.2.10 on 2020-06-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='shared_id_col',
        ),
        migrations.AddField(
            model_name='datasource',
            name='count_col',
            field=models.CharField(default='PatientID', max_length=128),
        ),
        migrations.CreateModel(
            name='DataSourceJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_src_col', models.CharField(max_length=64)),
                ('to_src_col', models.CharField(max_length=64)),
                ('from_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_data_source', to='idc_collections.DataSource')),
                ('to_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_data_source', to='idc_collections.DataSource')),
            ],
        ),
    ]
