# Generated by Django 2.2 on 2020-01-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0004_attribute_preformatted_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolrCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='solr_collections',
            field=models.ManyToManyField(to='idc_collections.SolrCollection'),
        ),
    ]
