# Generated by Django 2.2.13 on 2021-04-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0004_auto_20210125_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='aggregate_level',
            field=models.CharField(default='SeriesInstanceUID', max_length=128),
        ),
    ]
