# Generated by Django 2.2.18 on 2021-05-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0005_datasource_aggregate_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataversion',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
