# Generated by Django 2.2 on 2020-01-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0005_auto_20200124_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='solrcollection',
            name='version',
            field=models.CharField(default='1', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(choices=[('N', 'Continuous Numeric'), ('C', 'Categorical String'), ('T', 'Text'), ('S', 'String')], default='C', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='solrcollection',
            unique_together={('name', 'version')},
        ),
    ]
