# Generated by Django 2.2 on 2020-01-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0006_auto_20200126_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='version',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
