# Generated by Django 2.2.24 on 2022-01-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0007_auto_20211116_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_uuid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
