# Generated by Django 2.2.27 on 2022-04-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0008_collection_collection_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='source_url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
