# Generated by Django 2.2 on 2020-02-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0008_attribute_default_ui_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigQueryTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('version', models.CharField(max_length=4)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='bq_tables',
            field=models.ManyToManyField(to='idc_collections.BigQueryTable'),
        ),
    ]
