# Generated by Django 3.2.20 on 2023-08-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0009_collection_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cancer_type',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
