# Generated by Django 2.2 on 2020-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0011_bigquerytable_shared_id_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='solrcollection',
            name='shared_id_col',
            field=models.CharField(default='PatientID', max_length=128),
        ),
    ]
