# Generated by Django 2.2 on 2020-02-21 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0012_solrcollection_shared_id_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute_Ranges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('include_lower', models.BooleanField(default=True)),
                ('include_upper', models.BooleanField(default=True)),
                ('first', models.IntegerField(default=10)),
                ('last', models.IntegerField(default=80)),
                ('gap', models.IntegerField(default=10)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Attribute')),
            ],
        ),
    ]
