# Generated by Django 2.2 on 2020-02-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0014_auto_20200221_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_ranges',
            name='unbounded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attribute_ranges',
            name='include_upper',
            field=models.BooleanField(default=False),
        ),
    ]
