# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-04 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idc_collections', '0001_initial'),
        ('sharing', '0002_auto_20160614_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('shared', models.ManyToManyField(to='sharing.Shared_Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Cohort_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1024)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_comment', to='cohorts.Cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort_Perms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.CharField(choices=[('READER', 'Reader'), ('OWNER', 'Owner')], default='READER', max_length=10)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorts.Cohort')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Attribute')),
                ('feature_def', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idc_collections.User_Feature_Definitions')),
                ('resulting_cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorts.Cohort')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SET_OPS', 'Set Operations'), ('CLONE', 'Clone')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=1024)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_cohort', to='cohorts.Cohort')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_parent', to='cohorts.Cohort')),
            ],
        ),
    ]
