# Generated by Django 3.2.20 on 2023-10-25 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
