# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='data_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cohort',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
