# Generated by Django 2.2 on 2020-02-25 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idc_collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohorts', '0001_initial'),
        ('sharing', '0002_auto_20160614_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Attribute'),
        ),
        migrations.AddField(
            model_name='filters',
            name='feature_def',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idc_collections.User_Feature_Definitions'),
        ),
        migrations.AddField(
            model_name='filters',
            name='filter_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cohorts.Filter_Group'),
        ),
        migrations.AddField(
            model_name='filters',
            name='resulting_cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorts.Cohort'),
        ),
        migrations.AddField(
            model_name='filter_group',
            name='data_versions',
            field=models.ManyToManyField(to='idc_collections.DataVersion'),
        ),
        migrations.AddField(
            model_name='filter_group',
            name='resulting_cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorts.Cohort'),
        ),
        migrations.AddField(
            model_name='cohort_perms',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorts.Cohort'),
        ),
        migrations.AddField(
            model_name='cohort_perms',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cohort_comments',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_comment', to='cohorts.Cohort'),
        ),
        migrations.AddField(
            model_name='cohort_comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cohort',
            name='shared',
            field=models.ManyToManyField(to='sharing.Shared_Resource'),
        ),
    ]
