# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_auto_20160614_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samples',
            old_name='study',
            new_name='project',
        ),
    ]
