# Generated by Django 2.2 on 2020-02-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0007_collection_version'),
        ('cohorts', '0002_auto_20191205_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Attribute')),
                ('feature_def', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idc_collections.User_Feature_Definitions')),
            ],
        ),
        migrations.AddField(
            model_name='filters',
            name='filter_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cohorts.Filter_Group'),
        ),
    ]
