# Generated by Django 3.2.20 on 2023-10-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_datanode_programs'),
        ('cohorts', '0002_cohort_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.program'),
        ),
    ]
