# Generated by Django 2.2.10 on 2020-08-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0003_attribute_set_type_child_record_search'),
        ('cohorts', '0002_auto_20200630_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('numeric_op', models.CharField(blank=True, choices=[('B', '_btw'), ('GE', '_gte'), ('LE', '_lte'), ('G', '_gt'), ('L', '_lt')], max_length=4, null=True)),
                ('value_delimiter', models.CharField(default=',', max_length=4)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Attribute')),
                ('feature_def', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idc_collections.User_Feature_Definitions')),
                ('filter_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cohorts.Filter_Group')),
                ('resulting_cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorts.Cohort')),
            ],
        ),
        migrations.DeleteModel(
            name='Filters',
        ),
    ]
