# Generated by Django 2.2.13 on 2021-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_auto_20200915_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='case_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cohort',
            name='collections',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cohort',
            name='series_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cohort',
            name='study_count',
            field=models.IntegerField(default=0),
        ),
    ]
