# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_auto_20161114_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='cohort',
        ),
        migrations.AddField(
            model_name='samples',
            name='case_barcode',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='samples',
            name='sample_id',
            field=models.CharField(max_length=45,db_index=True),
        ),
        migrations.RenameField(
            model_name='samples',
            old_name='sample_id',
            new_name='sample_barcode',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
