# Generated by Django 2.2 on 2020-02-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_auto_20200204_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter_group',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='filter_group',
            name='feature_def',
        ),
        migrations.RemoveField(
            model_name='filter_group',
            name='value',
        ),
        migrations.AddField(
            model_name='filter_group',
            name='operator',
            field=models.CharField(choices=[('A', 'And'), ('O', 'Or')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='filter_group',
            name='resulting_cohort',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cohorts.Cohort'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filter_group',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
