# Generated by Django 2.2 on 2020-02-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0011_bigquerytable_shared_id_col'),
        ('cohorts', '0004_auto_20200206_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_group',
            name='version',
            field=models.ManyToManyField(to='idc_collections.DataVersion'),
        ),
    ]
