# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-21 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20160614_1131'),
        ('cohorts', '0004_auto_20161122_1238'),
        ('projects', '0005_auto_20161114_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='shared',
            field=models.ManyToManyField(to='sharing.Shared_Resource'),
        ),
        migrations.AddField(
            model_name='filters',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Program'),
        ),
    ]
