# Generated by Django 2.2.27 on 2022-06-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0005_auto_20220317_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='numeric_op',
            field=models.CharField(choices=[
                ('B', '_btw'), ('EB', '_ebtw'), ('BE', '_btwe'), ('EBE', '_ebtwe'), ('GE', '_gte'), ('LE', '_lte'), ('G', '_gt'), ('L', '_lt'), ('A', '_and'), ('O', '_or')
            ], default='O', max_length=4),
        ),
    ]
