# Generated by Django 2.2 on 2020-02-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0011_bigquerytable_shared_id_col'),
        ('cohorts', '0005_filter_group_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort_Collection_Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_group', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorts.Cohort')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc_collections.Collection')),
            ],
        ),
    ]
