# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0005_auto_20170320_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort_perms',
            name='perm',
            field=models.CharField(choices=[('READER', 'Reader'), ('OWNER', 'Owner')], default='READER', max_length=10),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('FILTERS', 'Filters'), ('SET_OPS', 'Set Operations'), ('PLOT_SEL', 'Plot Selections'), ('CLONE', 'Clone')], max_length=10),
        ),
    ]
