# Generated by Django 3.2.19 on 2023-06-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0007_auto_20220616_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='total_disk_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filter',
            name='operator',
            field=models.CharField(choices=[('B', '_btw'), ('EB', '_btwe'), ('BE', '_ebtw'),
                                            ('EBE', '_ebtwe'), ('GE', '_gte'), ('LE', '_lte'), ('G', '_gt'),
                                            ('L', '_lt'), ('A', '_and'), ('O', '_or')
                                            ], default='O', max_length=4),
        ),
        migrations.AlterField(
            model_name='filter_group',
            name='operator',
            field=models.CharField(choices=[('A', 'And'), ('O', 'Or')], default='A', max_length=1),
        ),
    ]
