# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked_emails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='shared_resource',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
